travis:
  secure:
    BINSTAR_TOKEN: ItFk385IEVDVbglH88P2fRaAvAxIYIS9sosMjn6jQwnUr9PjgyG6Sfb9IIoNP9snfnSwrp26V/4L9NfL8+Jb08ClatkE8Xx01maJlSVtHJpDQjnnT+4kkhdthUeH+NMYLTVywTT2kt4cufE0NosQdTtoIzM/j/tvE5jDBa8a90l+COlLMupMpM2NEOSmVKOGy2MM8gfz8J2uvbroVdF8f/W5uOoRO2VdP40ax8qCsWkZI4JrQ2nN/m4qjol6wo9A0H29tu2QiqUi4JIiINZ0vPgSy2OzDzJB8cfAI1pHfAoZtmG4tq3W3IrFpo4k9Gm7vC08KmJOim6p5tTfodeGSjlV36b/mqgCeTwuG4pSUCyRPTjF/ma9YRejSlz6Hnv5CrmP4LMPK6nWSElHKDIjgN+MsF8XVIWjZUTgIwxwX7bLgUa46CtY7au9akRodfcJ6gwfE7+zD6AjlXRv5+Hx8IqnA5oyKD/qrksmez8MF6vW6FCvWtjMn0VGHo1O/mZgqwnQkUmxYhitBiRH72l1qYYRbiPHyt8QXZi2v4VJhBjUvvJJrmIgsaxvj66ag4p94NJ6y9I1xL73RhvlSsnZA+mjLIA7ijRVQcm5rw+SW6xWOA7+aburI9hxCw87TbNHtPtIxBrFxQdNh/wTxGFsbuPFUJzk2dJjmlz2/pVoBoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
